# Generated by Django 3.1.1 on 2020-09-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200906_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comapny',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
